#!/usr/bin/env python
# coding: utf-8

import sys
import numpy as np
def permute(arr,i):
    if(i==len(arr)):
        return [[]]
    res_next=permute(arr,i+1)
    res=[]
    for n in arr[i]:
        for arr in res_next:
            res.append([n]+arr)
    return res

def compute(arr):
    x= permute(arr,0)
    print(', '.join(map(''.join, x)))

def main():
    filename = sys.argv[1]
    genArr(filename)

def genArr(filename):
     arr1 = np.genfromtxt(filename, delimiter=',',dtype=str)
     n=''
     temp = [[ele for ele in sub if ele != n] for sub in arr1] # pickled values
     compute(temp)

main()
